[project]
name = "acb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mmh3>=5.2.0",
    "mss>=10.1.0",
    "pynput>=1.8.1",
]
